### ISSUE TITLE
Error with prep_sample.R

### ISSUE THREAD

**Issue by udp3f** [leekgroup/recount-website#12]
Hi there,

I encountered an error with prep_sample.R, after the counts_exon_*.tsv is created. The error is for “SummarizedExperiment” object which says the number of rows in assay must equal number of rows in row data. I had successfully run rail-RNA on my fastq files and use the bigwig output. Here is how i run it
Rscript prep_sample.R -f ~/recount2/coverage_bigwigs/VCA.bw -c ~/recount2/cross_sample_results/counts.tsv.gz -b  /usr/local/bin/bwtool -w ~/src/WiggleTools/bin/wiggletools -a TRUE -d /Users/udp3f/recount2/tmp

Could you please suggest what could be the issue.

-Uma

**Comment by lcolladotor** [comment]
Hi Uma,

This looks like a duplicate of https://github.com/leekgroup/recount-website/issues/10 to me. Can you check that thread and see if the solution there applies to your use case?

Best,
Leonardo

**Comment by udp3f** [comment]
Hi Leonardo,
Yup! Thats the same error. Thank you so much for replying back.
-Uma

**Comment by lcolladotor** [comment]
No problem and good luck with your analysis ^^
