### ISSUE TITLE
Version number for the database

### ISSUE THREAD

**Issue by jrwalsh1** [leekgroup/recount-website#14]
Hi,

Is there versioning available for recount2 (beyond the global v2 label)?  I'd like to be able to see when additional (analysis-ready) data is added and check whether my local version is out of date.

**Comment by lcolladotor** [comment]
Hi,

We do have md5sum information for the files (check the `files.tsv`) files. You could maybe use that for tracking changes or "watch" the repo for any updates.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi,

Another option is to use `BiocFileCache::BiocFileCache()` when downloading the data. We'll do this natively in `recount3` and I might add it to the code in `recount` (the R package for the `recount2` project) later on.

Best,
Leo
