### ISSUE TITLE
request for standalone text files of counts

### ISSUE THREAD

**Issue by bzip2** [leekgroup/recount-website#15]
Hi. It would be great if you posted tab-delimited files for gene, transcript, exon and junction counts that contain all row and column identifiers and don't need to be joined with other files, at least for TCGA and GTEx. This wouldn't make the count text files much larger than they are, but it would make them useful. Currently, you need to extract data from R data frames whose structures differ for exons, genes, etc., and some of which are too large to load at once if you don't have enough memory; at least with text files, you can parse on the fly. For junctions and exons, I'd suggest including the gene and coordinates. Thanks.

Edit: I see the functionality in recount to download region-specific data, so the memory argument may not be valid, but I still think standalone text files would be useful.

**Comment by lcolladotor** [comment]
Hi,

The beauty of the _RangedSummarizedExperiment_ objects is that they hold together 3 or more tables (pieces of information) together:

* the feature information (`rowRanges()`),
* the sample information (`colData()`),
* and the count information (`assays()`). They can also store more than 1 assay.

I see why you suggest text files and the ability to parse them. But for now, you can create some of these files: for example, the genes and exons are always in the same order regardless of the study so you can extract the feature info for 1 study and use it for many. We do already provide text files for the counts (the largest portion of that matrix) and the raw bed-like jx files. 

Though, if you provide some template code for 1 small study to create exactly the type of files you want I could try to run it for the rest of the studies and the data uploaded. 

Best,
Leo
