### ISSUE TITLE
one-base exons in TCGA & GTEx data

### ISSUE THREAD

**Issue by bzip2** [leekgroup/recount-website#16]
Hi.

I might be doing something incorrect, but I find one-base and other short exons in TCGA and GTEx exon count data. I wasn't able to find an explanation in your Genome Biology paper, so I would appreciate a pointer if it's there somewhere.

Here is an example with a small file from TCGA:

```
> load("rse_exon_bile_duct.Rdata")               
> rse_exon@rowRanges[]   
GRanges object with 603139 ranges and 0 metadata columns:
                     seqnames                 ranges strand
                        <Rle>              <IRanges>  <Rle>
  ENSG00000000003.14     chrX [100627109, 100628669]      -
  ENSG00000000003.14     chrX [100628670, 100629986]      -
  ENSG00000000003.14     chrX [100630759, 100630866]      -
(...)
> rse_exon@rowRanges[520:522]  
GRanges object with 3 ranges and 0 metadata columns:
                     seqnames               ranges strand
                        <Rle>            <IRanges>  <Rle>
  ENSG00000001631.15     chr7 [92245913, 92245914]      -
  ENSG00000001631.15     chr7 [92245915, 92245915]      - <<<<<<<<<<<<<<<<<<<
  ENSG00000001631.15     chr7 [92245916, 92245920]      -
```

If these short exons are artifacts, are they "stealing" counts from legitimate exons? If so, is there a rational way to recapture these counts, like adding the counts to the longest overlapping exon, or is it safe to just ignore them? Should I be using derfinder?

Thanks.

**Comment by lcolladotor** [comment]
Hi,

Apologies for the brevity, but I'm at a conference right now. This can potentially happen when computing the _disjoint_ exons. Check the documentation tab at http://jhubiostatistics.shinyapps.io/recount and https://f1000research.com/articles/6-1558/v1.

Please let us know if that information resolves your question.

Best,
Leonardo
