### ISSUE TITLE
prep_merge does not work for junction file

### ISSUE THREAD

**Issue by gianmaz** [leekgroup/recount-website#18]
The deliverable "junctions.tsv.gz" is as described in RailRNA guideline:
junctions.tsv.gz: a labeled matrix whose (i, j)th element is the number of reads in sample j covering intron i. Introns are in the first column. Each one takes the form<chromosome>;<strand (+/-)>;<1-based start position (inclusive)>;<1-based end position (exclusive)>.

**The following part of prep_merge.R code does not work for the junction file junctions.tsv.gz.**

`## Code for creating rse_jx
message(paste(Sys.time(), 'reading', opt$jx_file))
jx_info <- read.table(opt$jx_file, sep = '\t', header = FALSE,
    stringsAsFactors = FALSE, check.names = FALSE)
colnames(jx_info) <- c('chr', 'start', 'end', 'sample_ids', 'reads')

## Create the counts matrix
message(paste(Sys.time(), 'processing count information'))
jx_info_samples <- strsplit(jx_info$sample_ids, ',')
jx_info_reads <- strsplit(jx_info$reads, ',')`

**Comment by lcolladotor** [comment]
Hi,

Can you show us the first 10 lines of the junction file please? Also, what is the actual error and R session information?

Best,
Leonardo

**Comment by gianmaz** [comment]
Dear Leonardo,
thanks for your quick reply.
Please, find below the info that you asked.
Please, let me know if you need additional info.

Thank you.
Best Regards,
Gianluca

error and traceback
[error_traceback.Rout.txt](https://github.com/leekgroup/recount-website/files/2329857/error_traceback.Rout.txt)

first 10 lines of junction file (generated in /cross_sample_results by rail-RNA)
[toy_junctions.txt](https://github.com/leekgroup/recount-website/files/2329810/toy_junctions.txt)

R session information
[merge_test.Rout.txt](https://github.com/leekgroup/recount-website/files/2329850/merge_test.Rout.txt)

**Comment by lcolladotor** [comment]
Hi @gianmaz,

Thanks for the files. The following R code reproduces your error:

```R
opt <- list(jx_file = 'toy_junctions.txt')
jx_info <- read.table(opt$jx_file, sep = '\t', header = FALSE,
    stringsAsFactors = FALSE, check.names = FALSE)
colnames(jx_info) <- c('chr', 'start', 'end', 'sample_ids', 'reads')
traceback()
```

output:

```R
> opt <- list(jx_file = 'toy_junctions.txt')
> jx_info <- read.table(opt$jx_file, sep = '\t', header = FALSE,
+     stringsAsFactors = FALSE, check.names = FALSE)
> colnames(jx_info) <- c('chr', 'start', 'end', 'sample_ids', 'reads')
Error in names(x) <- value : 
  'names' attribute [5] must be the same length as the vector [3]
> traceback()
1: `colnames<-`(`*tmp*`, value = c("chr", "start", "end", "sample_ids", 
   "reads"))
```

I can see that the junction file doesn't look right:

```R
> head(jx_info)
                      V1                      V2                          V3
1                        NA07048_male_CEU_UU-1-1 NA19129_female_YRI_UU_6-1-1
2 chr1;+;1020374;1022200                       1                           0
3 chr1;+;1043733;1043822                       1                           0
4 chr1;-;1312148;1312225                       1                           0
5 chr1;-;1321094;1324580                       1                           0
6 chr1;-;1398672;1398987                       0                           1
```

junction file contents:

```
	NA07048_male_CEU_UU-1-1	NA19129_female_YRI_UU_6-1-1
chr1;+;1020374;1022200	1	0
chr1;+;1043733;1043822	1	0
chr1;-;1312148;1312225	1	0
chr1;-;1321094;1324580	1	0
chr1;-;1398672;1398987	0	1
chr1;-;1542168;1543868	1	0
chr1;+;2559979;2560623	0	1
chr1;+;6073771;6082194	1	0
chr1;+;6090476;6094399	0	1
```

@nellore can the sample ids start at 0? Basically it looks like there are `;` instead of tabs for separating the first three columns (chr, start, end). Also, I'm not sure why there are sample names in the first line of the file.

@gianmaz regarding your R session information, we ended up using R 3.4.0 for most of this repo so I'm curious if that matters in your case (you are using R 3.3.1). I imagine that most if not all of the code should work with R 3.5 (the current latest release).

Best,
Leo

**Comment by gianmaz** [comment]
Dear @lcolladotor ,
thank you. I am running everything again on R 3.5. Everything seems to work fine.
However, if I am not wrong, the junctions file is generated by rail-RNA and is not processed in R before the prep_merge.R script. Am I correct?

@lcolladotor @nellore  How should the junctions file be like? Could it be anything to do with Rail-RNA version?

Thank you.
Best Regards,
Gianluca

**Comment by lcolladotor** [comment]
You'll get the same error with R 3.5 because like you said, the junction file is created by Rail-RNA. Lets wait for Abhi to check/answer your junction file question.

**Comment by gianmaz** [comment]
Dear @lcolladotor and @nellore ,
are there any news about the issues described in the comments above?

I hope you can help me. 
I really need to find a quick solution to this problem.
Thank you.
Gianluca

**Comment by nellore** [comment]
Hi Gianluca,

I think you’re using the wrong junctions file. You should be working with
first_pass_junctions.tsv.gz, which has a different format! Not sure this
was clear from the documentation.

Do you see this file?

Abhi

**Comment by gianmaz** [comment]
Hi Abhi, 
I run railRNA for multiple samples using default values in --deliverables.

The output folder ../**cross_sample_results contains:**
counts.tsv.gz
deletions.tsv.gz
insertions.tsv.gz
isofrags.tsv.gz
junctions.tsv.gz .  (which I am using)
normalization.tsv.gz

The output folder ../**junctions_and_indels contains**:
3 .bed files for each sample (deletions, insertion and junctions)

When I checked in railRNA support [http://docs.rail.bio/deliverables/ ](url)
I could not find any description for the first_pass_junctions.tsv.gz file that is why I used the other junction file.

Best Regards,
Gianluca

**Comment by nellore** [comment]
Try to use first_pass_junctions.tsv.gz, and see what happens when you run
the R scripts. You should get junction outputs you understand from this
process.

**Comment by gianmaz** [comment]
> Try to use first_pass_junctions.tsv.gz, and see what happens when you run
> the R scripts. You should get junction outputs you understand from this
> process.

Hi @nellore 

**I don't have any first_pass_junctions.tsv.gz.** 
I listed the content of the output directory above (no first_pass_junctions file among them).
The first_pass_junctions is also not described in railRNA support webpage.

**Comment by lcolladotor** [comment]
I'm closing this issue since it's been inactive for some time.

Best,
Leo
