### ISSUE TITLE
SRP051606, 3 samples missing

### ISSUE THREAD

**Issue by sumitpaliwal** [leekgroup/recount-website#21]
Hi, 
I wanted to perform some analysis using Recount2 data from SRP051606. However, I find that 3 samples (SRR1736492,SRR1736495, and SRR1736498) are missing.
` colData(rse_gene)$run`
> [1] "SRR1736482" "SRR1736483" "SRR1736484" "SRR1736485" "SRR1736486" "SRR1736487" "SRR1736488" "SRR1736489"
 [9] "SRR1736490" "SRR1736491" "SRR1736493" "SRR1736494" "SRR1736497" "SRR1736496" "SRR1736499" "SRR1736500"
[17] "SRR1736501" "SRR1736502" "SRR1736503" "SRR1736505" "SRR1736504" "SRR1736507" "SRR1736506" "SRR1736508"
[25] "SRR1736509" "SRR1736510

Although, in the  project it mentions 29 samples, I find data for only 26.

**Comment by lcolladotor** [comment]
Hi @sumitpaliwal,

This could be the result of two things:

* the aligner behind `recount2`, `Rail-RNA` might have had trouble pulling the data from SRA back on 2016 when we ran it and might have not been able to download data for these 3 samples.
* SRA added the description for these 3 samples after we ran the aligner.

Best,
Leo
