### ISSUE TITLE
Rail web server error

### ISSUE THREAD

**Issue by millerh1** [leekgroup/recount-website#24]
Hello!

When trying to access the RAIL server from Recount2, I got an error. Here is the link: http://duffel.rail.bio/recount/v2/SRP025982/rse_gene.Rdata

Here is the error:
![image](https://user-images.githubusercontent.com/44813811/102783100-6e3bba80-4368-11eb-8a49-cfd5bdbab47a.png)

**Comment by lcolladotor** [comment]
Hi,

Abhi @nellore has been looking into the issue with the service that hosts duffel.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi,

I don't remember when this was fixed, but it works now so I'll be closing the issue. Thanks for reporting it!

Best,
Leo
