### ISSUE TITLE
Unable to click download links in Chrome?

### ISSUE THREAD

**Issue by cmdcolin** [leekgroup/recount-website#25]
Currently if I visit https://jhubiostatistics.shinyapps.io/recount/ in google chrome, I am not able to click links in the table for downloads. I'm not exactly sure but it might be due to the links being http and the hosting page is https

Copying the link and pasting into a new tab or into wget works
Firefox also works (after a short wait time after link click)

**Comment by lcolladotor** [comment]
Hm.... this might have to do with the `DT` package and/or `shiny`. hm..

Thanks for the report!

**Comment by lcolladotor** [comment]
I was finally able to figure out a solution to this issue. Have a great 2024 winter break!

Best,
Leo
