### ISSUE TITLE
Availability of bigwig files?

### ISSUE THREAD

**Issue by cmdcolin** [leekgroup/recount-website#26]
Hi there,

Do you have the bigwig files for recount available? I tried to manually stitch together what I thought the link format might be e.g. 

http://duffel.rail.bio/recount/v2/SRP042161/mean_SRP042161.bw

this is a 404 however

Separate issue here from the google chrome just to stay on target :)

**Comment by cmdcolin** [comment]
Just in case it helps gauge how I approach the recount project, I'm just looking for interesting examples of single cell data to plot, and thought recount might be a good example of precomputed data for this!

**Comment by lcolladotor** [comment]
Hi,

Thank you for your interest in the _recount2_ project (`recount` R package).

You can use `download_study()` to get download the per-sample BigWig files https://github.com/leekgroup/recount/blob/master/R/download_study.R#L34. You could also use the newer `recount3` project and find the URLs using `create_rse()$BigWigURL` like at http://research.libd.org/recount3/reference/create_rse.html.

Best,
Leo
