### ISSUE TITLE
Access to novel exons using referenence free quantification

### ISSUE THREAD

**Issue by yuzhong1997** [leekgroup/recount-website#27]
To whom it may concern,

Hi, I'm just wondering in recount2 compilation, if novel exons have been taken into account for and integrated into your resources?
For example, regular pipeline quantify exon expression based on annotation, with lossing information of novel exons within isoforms. Stringtie/Stringtie2 can usually reveal novel exons specficlly expressed in samples. 

I'm not sure if recount2 intergrate some functionality of such Stringtie2 to reveal novel exons, other than well annotated ones in Gencode. Thanks.

Best,

Yu

**Comment by lcolladotor** [comment]
Hi Yu @yuzhong1997,

The "exons" you can download from the `recount2` project are all annotated ones. However, the exon-exon junctions include novel (non-annotated) exon-exon junctions.

If you have the coordinates for a novel exon, you can use the BigWig files provided by `recount2` to quantify expression there. Similar to how we do for "expressed regions". In that case, `recount::coverage_matrix()` or other tools might be useful https://leekgroup.github.io/recount/reference/coverage_matrix.html.

Best,
Leo
