### ISSUE TITLE
would it be possible to set a filter by tissue of analysis?

### ISSUE THREAD

**Issue by lfresard** [leekgroup/recount-website#4]
Hi,
First thanks a lot for this work, it's really nice to be able to access this data.
I wondered if it would be possible to set a filter by tissue to select only studies that have the tissue of interest. 
It seems that when I look for one tissue in the search field, it's matching the abstract but not the actual tissue of analysis. Maybe am doing it the wrong way too, I would love to know the most direct way to restrict by tissue.
Thanks a lot in advance!
Best,
Laure

**Comment by lcolladotor** [comment]
Hi Laure,

The search box only searches the abstracts of the studies. The metadata for most studies in the Sequence Read Archive is not well organized, so we can't provide the tissue search box you are looking for. You can get an idea of how hard this could be by checking http://bioconductor.org/packages/release/bioc/vignettes/recount/inst/doc/recount-quickstart.html#finding-phenotype-information. You could try using the `sharq_beta_tissue` column for several SRA studies to then find the SRA studies of interest. Something like:

```R
> library(recount)
> m <- all_metadata('sra')
> table(m$sharq_beta_tissue, useNA = 'ifany')

 adipose tissue   adrenal gland           blood    blood vessel            bone 
            454              33            2019              61             242 
          brain          breast          cervix           colon      epithelium 
           1083            1489             712             332             825 
          heart       intestine          kidney           liver            lung 
            427            1695             652             219             353 
       melanoma       monocytes          muscle           ovary        pancreas 
             83              86             668              28              40 
          penis        placenta        prostate            skin     spinal cord 
             41             165             464             567             184 
         spleen       stem cell          testis          tonsil  umbilical cord 
             75            1271              48             461             765 
urinary bladder            <NA> 
             47           34510 
> table(m$project[m$sharq_beta_tissue == 'liver' & !is.na(m$sharq_beta_tissue)])

SRP000599 SRP000941 SRP001558 SRP002272 SRP003227 SRP003754 SRP007338 SRP007359 SRP007412 
       30         2        12        15         1         6         1         1         3 
SRP007461 SRP007494 SRP007560 SRP007862 SRP009123 SRP009266 SRP009862 SRP010670 SRP011233 
       12         1         4         1         6         2         9         2         8 
SRP012096 SRP012098 SRP012099 SRP014320 SRP015845 SRP019807 SRP022054 SRP026084 SRP028738 
        4         8         7         9         6         1         9         4         4 
SRP029334 SRP033131 SRP033566 SRP035387 SRP039694 SRP041597 SRP045048 
        5         8         1         7        16         2        12 
```

GTEx and TCGA have their own specific tissue columns.

Best,
Leonardo

**Comment by lfresard** [comment]
Hi Leonardo,
Thanks a lot for your answer!
I assumed it was not that simple to set it for all studies. Thank you for the example through phenotypes, will do that way.
Have a great day,
Best,
Laure

**Comment by jtleek** [comment]
Laure

But stay tuned our next project is improving the metadata should have
something in the next couple of months!

Jeff

**Comment by lfresard** [comment]
Sounds great!
Thanks
Laure

**Comment by lcolladotor** [comment]
Like @ShanEllis pointed out to me, I should mention that the `sharq_beta*` columns in the metadata are based on natural language processing results on the abstracts. This is mentioned in the `documentation` tab of https://jhubiostatistics.shinyapps.io/recount/. It's also mentioned in the pre-print. In any case, you can find more information about SHARQ beta at http://www.cs.cmu.edu/~ckingsf/sharq/.
