### ISSUE TITLE
Missing column names for tsv files.

### ISSUE THREAD

**Issue by simonvh** [leekgroup/recount-website#5]
Thanks for a great resource. When I download tsv files from the recount2 website (for instance, the GTEx data http://duffel.rail.bio/recount/SRP012682/counts_gene.tsv.gz), I have no way of linking this to genes. It seems the column names are missing. Are these available? Would be useful to have them in the file.

**Comment by lcolladotor** [comment]
Hi,

The `counts_gene_tsv.gz` files do include column names. They are the SRA run id except for TCGA. You are right that they don't have row names as we didn't save them in https://github.com/leekgroup/recount-website/blob/b136893e22fb46efc066de47896bdc57283f2b97/rse/create_rse.R#L588-L592. You can still get the gene information by looking at the R information. 

```
> library('recount')
> rowRanges(rse_gene_SRP009615)
GRanges object with 58037 ranges and 3 metadata columns:
                     seqnames                 ranges strand |            gene_id bp_length          symbol
                        <Rle>              <IRanges>  <Rle> |        <character> <integer> <CharacterList>
  ENSG00000000003.14     chrX [100627109, 100639991]      - | ENSG00000000003.14      4535          TSPAN6
   ENSG00000000005.5     chrX [100584802, 100599885]      + |  ENSG00000000005.5      1610            TNMD
  ENSG00000000419.12    chr20 [ 50934867,  50958555]      - | ENSG00000000419.12      1207            DPM1
  ENSG00000000457.13     chr1 [169849631, 169894267]      - | ENSG00000000457.13      6883           SCYL3
  ENSG00000000460.16     chr1 [169662007, 169854080]      + | ENSG00000000460.16      5967        C1orf112
                 ...      ...                    ...    ... .                ...       ...             ...
   ENSG00000283695.1    chr19 [ 52865369,  52865429]      - |  ENSG00000283695.1        61              NA
   ENSG00000283696.1     chr1 [161399409, 161422424]      + |  ENSG00000283696.1       997              NA
   ENSG00000283697.1     chrX [149548210, 149549852]      - |  ENSG00000283697.1      1184    LOC101928917
   ENSG00000283698.1     chr2 [112439312, 112469687]      - |  ENSG00000283698.1       940              NA
   ENSG00000283699.1    chr10 [ 12653138,  12653197]      - |  ENSG00000283699.1        60         MIR4481
  -------
  seqinfo: 25 sequences (1 circular) from an unspecified genome; no seqlengths
> 
```

All gene count matrices are in the same order so you can write the gene info to a text file once and use it all for all the datasets you want to look at. _RangedSummarizedExperiment_ objects are far superior to text files (counts, phenotype, gene info) which is why we mostly use those. 


Best,
Leo

**Comment by simonvh** [comment]
I indeed meant the row names, sorry for the confusion. It's good to know they are always in the same order, thanks! Would it be a lot of trouble to add them? Or to add a flat text file with the information for download? It would save time and effort for those of us who don't regularly work with R. I did resort to using the Rdata files, but it did take me some time to work out how a RangedSummarizedExperiment works... Essentially, when the row identifiers are available, everything can be downloaded as .tsv without a dependency on R. Would be nice, although I completely understand that there might be other priorities. :) Thanks for the reply!

**Comment by nuno-agostinho** [comment]
> All gene count matrices are in the same order

Files containing gene and exon counts are indeed in the same order. However, this is not true for files containing junction counts (e.g. they do not have the same number of lines). Could you please fix these files? Thank you.

**Comment by lcolladotor** [comment]
Hi @nuno-agostinho,

Can you explicitly recommend an alternative sentence? Or are you saying that `gene` should be in bold?
