### ISSUE TITLE
Line 130 'exons' should be replaced by 'exon'

### ISSUE THREAD

**Issue by zhaleh-safikhani** [leekgroup/recount-website#6]
## Load exons info
exon <- recount_exons

## Create rse_exon
exons_all <- unlist(exons)
Error in unlist(exons) : object 'exons' not found

**Comment by zhaleh-safikhani** [comment]
in prep_sample.R

**Comment by lcolladotor** [comment]
Fixed in https://github.com/leekgroup/recount-website/commit/022c3803e2116c273e1d8681b9cdc3e245ca241c
