### ISSUE TITLE
wiggletools arises error

### ISSUE THREAD

**Issue by zhaleh-safikhani** [leekgroup/recount-website#7]
in prep_sample.R 
I had to replace 
system(paste(opt$wiggletools, 'AUC', auc_file, bw))
by
system(paste(opt$wiggletools, 'print' , auc_file, 'AUC', bw))
to make it work!

**Comment by lcolladotor** [comment]
Which version of wiggletools were you using?

**Comment by zhaleh-safikhani** [comment]
1.2
I cloned the last version from github.

**Comment by lcolladotor** [comment]
Ok, thanks! I changed the default code to match your version.

Best,
Leo
