### ISSUE TITLE
prep_sample.R bug

### ISSUE THREAD

**Issue by zhaleh-safikhani** [leekgroup/recount-website#9]
genes <- recount_genes
counts_gene <- lapply(split(as.data.frame(exon_counts), count_groups), colSums)
counts_gene <- do.call(rbind, counts_gene)
Error: object 'genes' not found

**Comment by lcolladotor** [comment]
Hm... that's weird since you just created the `genes` object int he first line of code you posted.

**Comment by zhaleh-safikhani** [comment]
ah it's because in your version it was 'gene' I changed it to 'genes' to make it work on my local machine! Anyway just wanted to let you know that so you can debug the github version

**Comment by lcolladotor** [comment]
Yeah, I realized that after double checking the code. Thanks for the bug reports!
